# Generated by Django 2.1.8 on 2019-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='None', upload_to='images/blog_images')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='None', max_length=300)),
                ('title', models.CharField(default='None', max_length=300)),
                ('framework', models.CharField(default='None', max_length=300)),
                ('languages', models.CharField(default='None', max_length=300)),
                ('description', models.TextField(default='None', max_length=1000)),
                ('image', models.ImageField(default='None', upload_to='images/project_images')),
                ('carousel_image1', models.ImageField(default='None', upload_to='images/project_images')),
                ('carousel_image2', models.ImageField(default='None', upload_to='images/project_images')),
                ('carousel_image3', models.ImageField(default='None', upload_to='images/project_images')),
                ('carouselTitle', models.CharField(default='None', max_length=300)),
                ('video', models.FileField(default='None', upload_to='videos/project_videos')),
                ('project_url', models.URLField(default='None', max_length=500)),
                ('github_url', models.URLField(default='None', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeHardCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV', models.FileField(default='None', upload_to='pdf/hard_copy_CV')),
                ('coverletter', models.FileField(default='None', upload_to='pdf/hard_copy_cover_letter')),
            ],
        ),
    ]
