# Generated by Django 2.1.8 on 2019-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='carousel_image1',
            field=models.URLField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='carousel_image2',
            field=models.URLField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='carousel_image3',
            field=models.URLField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='None', max_length=500),
        ),
    ]
